# Generated by Django 2.1.1 on 2018-09-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180926_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='username',
        ),
        migrations.RemoveField(
            model_name='following',
            name='username',
        ),
        migrations.DeleteModel(
            name='followers',
        ),
        migrations.DeleteModel(
            name='following',
        ),
    ]
