# Generated by Django 2.1.2 on 2018-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic'),
        ),
    ]
