# Generated by Django 2.1.2 on 2018-10-04 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0008_auto_20181003_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='postuploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postpic', models.ImageField(blank=True, upload_to='postpic')),
                ('posttime', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='postpic',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='posttime',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='profilepic',
            field=models.ImageField(blank=True, default='face.jpg', null=True, upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
