# Generated by Django 2.1.2 on 2018-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_auto_20181004_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuploads',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postuploads',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
