# Generated by Django 2.1.2 on 2018-10-04 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20181004_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuploads',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
